import int_libs = libpng%lib{png}
import imp_libs = libwebp%lib{webp}

if ($cxx.id == 'gcc')
{
  import int_libs += lib{stdc++fs}
}

lib{headsurgeon}: {hxx cxx}{** -version} hxx{version} $imp_libs $int_libs

hxx{version}: in{version} $src_root/manifest
hxx{version}:
{
  dist  = true
  clean = ($src_root != $out_root)
}

cxx.poptions =+ "-I$out_root" "-I$src_root"

obja{*}: cxx.poptions += -DLIBHEADSURGEON_STATIC_BUILD
objs{*}: cxx.poptions += -DLIBHEADSURGEON_SHARED_BUILD

lib{headsurgeon}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $int_libs
}

liba{headsurgeon}: cxx.export.poptions += -DLIBHEADSURGEON_STATIC
libs{headsurgeon}: cxx.export.poptions += -DLIBHEADSURGEON_SHARED

if $version.pre_release
  lib{headsurgeon}: bin.lib.version = @"-$version.project_id"
else
  lib{headsurgeon}: bin.lib.version = @"-$version.major.$version.minor"

{hxx}{*}:
{
  install = include/libheadsurgeon/
  install.subdirs = true
}
