import libs += libui%lib{ui} libheadsurgeon%lib{headsurgeon}

if ($cc.target.class == 'linux')
{
  import libs += lib{pthread}
}

exe{hsgui}: {hxx ixx txx cxx}{**} $libs

cxx.poptions =+ "-I$out_root" "-I$src_root"
