import libs = libheadsurgeon%lib{headsurgeon} cli11%lib{cli11}

if ($cxx.stdlib == 'libstdc++')
{
  import libs += lib{stdc++fs}
}
elif ($cxx.stdlib == 'libc++')
{
  import libs += lib{c++experimental}
}

exe{hsdmi}: {cxx}{*} $libs

cxx.poptions =+ "-I$out_root" "-I$src_root"
